config/routes.rb
Rails.application.routes.draw do
  
  resources :reviews
  resources :applications
  devise_for :gyms, path_names: { sign_in: 'login', sign_out: 'logout'}
  devise_for :trainers, path_names: { sign_in: 'login', sign_out: 'logout'}
  devise_for :trainees,path_names: { sign_in: 'login', sign_out: 'logout'}
  root to:'home#index'
  get'home/about', to: 'home#about'
  get'home/category', to:'home#category'
  resources :gyms
  resources :trainers
  resources :trainees
end

app/models/gym.rb
class Gym < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :applications
    has_many :trainers
    validates :email, presence: true , uniqueness: true
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: %i[ show edit update destroy ]
  before_action :gym_signed_in unless Rails.env.test?
  # GET /gyms or /gyms.json
  def index
    @gyms = Gym.all
  end

  # GET /gyms/1 or /gyms/1.json
  def show
  end

  # GET /gyms/new
  def new
    @gym = Gym.new
  end

  # GET /gyms/1/edit
  def edit
  end

  # POST /gyms or /gyms.json
  def create
    @gym = Gym.new(gym_params)

    respond_to do |format|
      if @gym.save
        format.html { redirect_to gym_url(@gym), notice: "Gym was successfully created." }
        format.json { render :show, status: :created, location: @gym }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyms/1 or /gyms/1.json
  def update
    respond_to do |format|
      if @gym.update(gym_params)
        format.html { redirect_to gym_url(@gym), notice: "Gym was successfully updated." }
        format.json { render :show, status: :ok, location: @gym }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gym.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyms/1 or /gyms/1.json
  def destroy
    @gym.destroy
    respond_to do |format|
      format.html { redirect_to gyms_url, notice: "Gym was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  
    # Only allow a list of trusted parameters through.
    def gym_params
      params.require(:gym).permit(:name,:email,:password)
    end
end

app/helpers/gyms_helper.rb
module GymsHelper
end

app/views/gyms/_form.html.erb
<%= form_with(model: gym, local: true) do |form| %>
  <% if gym.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym.errors.count, "error") %> prohibited this gym from being saved:</h2>

      <ul>
        <% gym.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>


  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

<div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.password_field :contact %>
  </div>

  <div class="field">
    <%= form.label :fees %>
    <%= form.text_field :fees %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :owner_name %>
    <%= form.text_field :owner_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gyms/edit.html.erb
<h1>Edit Gym profile</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Show', @gym %> |
<%= link_to 'Back', gyms_path %>

app/views/gyms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gyms</h1>

<table>
  <thead>
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>City</th>
    <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @gyms.each do |gym| %>
      <tr>
      <td><%=gym.name%></td>
      <td><%=gym.email%></td>
      <td><%=gym.city%></td>
        <td><%= link_to 'Show', gym %></td>
        <% if logged_in? && gym = current_user%>
        <td><%= link_to 'Edit', edit_gym_path(gym) %></td>
        <td><%= link_to 'Destroy', gym, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gyms/new.html.erb
<h1>Gym profile</h1>

<%= render 'form', gym: @gym %>

<%= link_to 'Back', gyms_path %>

app/views/gyms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gym_path(@gym) %> |
<%= link_to 'Back', gyms_path %>